### ISSUE TITLE
Only grabs top 2 grids, would be awesome if it grabbed everything

### ISSUE THREAD

**Issue by seanmc9** [dcts/opensea-scraper#2]
I would like to be able to scrape all of the cards on a page for Id information, but I found that as currently implemented, this scraper only actually grabs the top 2-6 with this line in `OpenseaScraper.js` `const cardsNodeList = document.querySelectorAll(".Asset--anchor");`. This works great for finding the floor, but what if I wanted to grab all of the cards, would this be possible? I tried a couple other options like `querySelectorAll`ing on `'[role="gridcell"]'` but ultimately found no improvement - would you have any ideas on why it isn't able to grab the whole page worth of cards? Thanks so much!

**Comment by dcts** [comment]
Hey, how many cards would you want to grab? Because the page dynamically loads the items and replaces the old ones. You can see that behavior if you check the DOM and scroll... Heres a screenshare of the DOM during scrolling:
![gif-scrolling](https://user-images.githubusercontent.com/44790691/131911754-443fd72a-4f2f-40b7-a9b0-0bb6343faa9c.gif)

Hope you can see that the amount of elements within the grid (all elements with `role="gridcell"`) dynamically adapts. New elements get added, and more importantly, older elements get removed. So even If you scroll through the whole collection and run your query selector operation at the end you would olny get the last elements unfortunately.

The way I would implement that is: 
- get the parent component, in our case that would be the grid => `document.querySelector(".AssetsSearchView--assets")`
- create a [Mutation observer](https://developer.mozilla.org/de/docs/Web/API/MutationObserver) on that element
- with the mutation observer you can implement a callback function that triggeres, everytime the element changes. So when a new element gets added you can extract the info you need 
- when the mutation observer is set, you would need to manually implement the scrolling behaviour

Its not the most difficult task but also not that trivial. Hope that helps!

**Comment by dcts** [comment]
@Jethro87 I like the idea to return more information, if you want to implement it, feel free, I can also help. I have implemented a scraper for the rankigs with scroll functionality (if you want to fetch more than the first 5 items) that works without having a mutations observer. 

I would suggest to have another function (for example) `OpenseaScraper.getOffers(slug, n)` that returns an array of items, for example:
![ccnft](https://user-images.githubusercontent.com/44790691/137905782-9de4e567-b8ee-4d11-8771-d5d54ce778ec.png)
```js
const items = OpenseaScraper.getOffers("cool-cats-nft", 3);
[
  {
    tokenId: 5265,
    price: {
      currency: "ETH",
      amount: 7.82
    }
  },
  {
    tokenId: 2878,
    price: {
      currency: "ETH",
      amount: 7.9
    }
  },
  {
    tokenId: 6218,
    price: {
      currency: "ETH",
      amount: 7.9
    }
  }
]
```

**Comment by alex-pcln** [comment]
@dcts has this functionality been removed? I find it very useful to be able to scroll down and get more results.

**Comment by dcts** [comment]
@alex-pcln how many items do you need from a given page? Because in the current version of the scraper you get the top 32 offers. Simply run:
```js
let result = await OpenseaScraper.offers("cool-cats-nft");
```

If you need more than the top 32 offers you might want to downgrade to v2 or similar. If you want I can lookup the exact version if thats usefull to you. But I am wondering in what use case you would need more than 32 offers? 🤔

**Comment by alex-pcln** [comment]
Thanks @dcts I downgraded to commit `e01fea03e3` where it is still there.

Yes I need more than 32, actually I need all assets of a collection that are currently on sale. Unfortunately, it seems that I cannot get that from their API, so I'm using your scrapper. I just need to do some changes to detect the currency.

**Comment by dcts** [comment]
Well if you need more than 32 items we should bring that functionality back, and maybe call the function `offersByScrolling`. If thats usefull to you I don't see any downside. I can add it back in.

**Comment by alex-pcln** [comment]
That would be great, thanks. It's not the most efficient way to get all assets for sale but I couldn't find any other way at the moment.

**Comment by dcts** [comment]
@alex-pcln which of the following methods do you need?
- **`offersByScrolling`** : you input the slug of the collection you want to fetch, for example `cool-cats-nft`.
- **`offersByScrollingByUrl`** : you input the url that points to a filtered collection, for example `https://opensea.io/collection/boredapeyachtclub?search[sortAscending]=true&search[sortBy]=PRICE&search[stringTraits][0][name]=Background&search[stringTraits][0][values][0]=Purple&search[stringTraits][1][name]=Earring&search[stringTraits][1][values][0]=Silver%20Hoop&search[stringTraits][2][name]=Eyes&search[stringTraits][2][values][0]=Bloodshot&search[toggles][0]=BUY_NOW`

**Comment by dcts** [comment]
migrated to issue #29
